In [7]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.io import loadmat
import warnings
warnings.filterwarnings('ignore')

In [5]:
data_path = "../Monkeys A B/"

In [6]:
os.listdir(data_path)

['monkeyB_nicknamed_Pop', 'monkeyA_nicknamed_Puddle']

In [8]:
file_path = os.path.join(data_path, 'monkeyA_nicknamed_Puddle/Dorsal PFC/Puddle_lPFC_5ch_dorsal/Pud20141217a_ch60_1.mat')
data = loadmat(file_path)

In [10]:
data

{'__header__': b'MATLAB 5.0 MAT-file, Platform: PCWIN64, Created on: Sun Jul  2 22:18:38 2023',
 '__version__': '1.0',
 '__globals__': [],
 'TrialID': array([[array(['Task_Mode'], dtype='<U9'),
         array(['Target_Location'], dtype='<U15'),
         array(['Target_Number'], dtype='<U13'), ...,
         array(['Spatial_Orientation'], dtype='<U19'),
         array(['FP_Pos_Idx'], dtype='<U10'),
         array(['Arr_Pos_Idx'], dtype='<U11')],
        [array([[1.]], dtype=float32), array([[2, 4]], dtype=uint8),
         array([[2]], dtype=uint8), ..., array([[0]], dtype=int8),
         array([[1]], dtype=uint8), array([[1]], dtype=uint8)],
        [array([[1.]], dtype=float32), array([[2, 4]], dtype=uint8),
         array([[2]], dtype=uint8), ..., array([[0]], dtype=int8),
         array([[1]], dtype=uint8), array([[1]], dtype=uint8)],
        ...,
        [array([[2.]], dtype=float32), array([[2]], dtype=uint8),
         array([[1]], dtype=uint8), ..., array([[1]], dtype=int8),
      

In [13]:
trial_header = [
    str(item[0]) if isinstance(item, np.ndarray) and len(item) > 0 else "Unknown"
    for item in data['TrialID'][0]
]
trial_data = []
for row in data['TrialID'][1:]:
    processed_row = []
    for item in row:
        if isinstance(item, np.ndarray) and item.size > 0:
            # Handle nested arrays
            if isinstance(item[0], np.ndarray) and len(item[0]) > 0:
                processed_row.append(item[0][0])  # Access inner value
            else:
                processed_row.append(item[0])  # Access first element
        else:
            processed_row.append(None)  # Use None for empty or unexpected data
    trial_data.append(processed_row)
    
trial_df = pd.DataFrame(trial_data, columns=trial_header)

# Processing `fname`
fname = data['fname'][0]

# Processing `t_trig`
t_trig_header = [str(item[0]) for item in data['t_trig'][0]]
t_trig_data = [
    [item[0][0] if isinstance(item, np.ndarray) else item for item in row]
    for row in data['t_trig'][1:]
]
t_trig_df = pd.DataFrame(t_trig_data, columns=t_trig_header)

# Processing `t_spike` (if needed, flatten further depending on the requirement)
t_spike_data = [item[0].tolist() for item in data['t_spike']]
t_spike_df = pd.DataFrame(t_spike_data)

# Saving to CSV
trial_df.to_csv('TrialID.csv', index=False)
t_trig_df.to_csv('t_trig.csv', index=False)
t_spike_df.to_csv('t_spike.csv', index=False)

# Output filenames for reference
print("Files created:")
print(" - TrialID.csv")
print(" - t_trig.csv")
print(" - t_spike.csv")


Files created:
 - TrialID.csv
 - t_trig.csv
 - t_spike.csv


In [14]:
print(trial_df.shape)

(1667, 16)


In [15]:
print(t_trig_df.shape)

(1667, 9)


In [18]:
len(t_spike_df[0][0])

6743